
import sys
from awsglue.transforms import *
from awsglue.utils import getResolvedOptions
from pyspark.context import SparkContext
from awsglue.context import GlueContext
from awsglue.job import Job
 
sc = SparkContext.getOrCreate()
glueContext = GlueContext(sc)
spark = glueContext.spark_session
job = Job(glueContext)
import pyspark.sql.functions as f
path_cotacao = 's3://trusted-zone-echo/ods/sf/cotacoes/'
df_cotacao = spark.read.parquet(path_cotacao)
df_cotacao = df_cotacao.select(
    f.coalesce(f.col("accountid"), f.lit("N/A")).alias("idconta_cotacao"),
    f.coalesce(f.col("additionaladdress"), f.lit("N/A")).alias("enderecofulladicional_cotacao"),
    f.coalesce(f.col("additionalcity"), f.lit("N/A")).alias("cidadeadicional_cotacao"),
    f.coalesce(f.col("additionalcountry"), f.lit("N/A")).alias("paisadicional_cotacao"),
    f.coalesce(f.col("additionalgeocodeaccuracy"), f.lit("N/A")).alias("geocodeadicional_cotacao"),
    f.coalesce(f.col("additionallatitude"), f.lit("N/A")).alias("latitudeadicional_cotacao"),
    f.coalesce(f.col("additionallongitude"), f.lit("N/A")).alias("longitudeadicional_cotacao"),
    f.coalesce(f.col("additionalname"), f.lit("N/A")).alias("nomeadicional_cotacao"),
    f.coalesce(f.col("additionalpostalcode"), f.lit("N/A")).alias("cepadicional_cotacao"),
    f.coalesce(f.col("additionalstate"), f.lit("N/A")).alias("estadoadicional_cotacao"),
    f.coalesce(f.col("additionalstreet"), f.lit("N/A")).alias("enderecoadicional_cotacao"),
    f.coalesce(f.col("alcada_de_aprovacao__c"), f.lit("N/A")).alias("alcadadeaprovacao_cotacao"),
    f.coalesce(f.col("billingaddress"), f.lit("N/A")).alias("enderecofullcobranca_cotacao"),
    f.coalesce(f.col("billingcity"), f.lit("N/A")).alias("cidadecobranca_cotacao"),
    f.coalesce(f.col("billingcountry"), f.lit("N/A")).alias("paiscobranca_cotacao"),
    f.coalesce(f.col("billinggeocodeaccuracy"), f.lit("N/A")).alias("geocodecobranca_cotacao"),
    f.coalesce(f.col("billinglatitude"), f.lit("N/A")).alias("latitudecobranca_cotacao"),
    f.coalesce(f.col("billinglongitude"), f.lit("N/A")).alias("longitudecobranca_cotacao"),
    f.coalesce(f.col("billingname"), f.lit("N/A")).alias("nomecobranca_cotacao"),
    f.coalesce(f.col("billingpostalcode"), f.lit("N/A")).alias("cepcobranca_cotacao"),
    f.coalesce(f.col("billingstate"), f.lit("N/A")).alias("estadocobranca_cotacao"),
    f.coalesce(f.col("billingstreet"), f.lit("N/A")).alias("enderecocobranca_cotacao"),
    f.coalesce(f.col("cancreatequotelineitems"), f.lit("N/A")).alias("podecriar linhasdecotacao_cotacao"),
    f.coalesce(f.col("cliente_vip__c"), f.lit("N/A")).alias("clientevip_cotacao"),
    f.coalesce(f.col("consumo_fora_ponta_kwh__c"), f.lit("N/A")).alias("consumoforapontakwh_cotacao"),
    f.coalesce(f.col("consumo_ponta_kwh__c"), f.lit("N/A")).alias("consumopontakwh_cotacao"),
    f.coalesce(f.col("contactid"), f.lit("N/A")).alias("idcontato_cotacao"),
    f.coalesce(f.col("contractid"), f.lit("N/A")).alias("idcontrato_cotacao"),
    f.coalesce(f.col("createdbyid"), f.lit("N/A")).alias("criadopor_cotacao"),
    f.coalesce(f.col("createddate"), f.lit("N/A")).alias("datacriacao_cotacao"),
    f.coalesce(f.col("custo_adequacao__c"), f.lit("N/A")).alias("custoadequacao_cotacao"),
    f.coalesce(f.col("de_desconto_ofertado__c"), f.lit("N/A")).alias("decontoofertado_cotacao"),
    f.coalesce(f.col("demanda_fora_ponta_kw__c"), f.lit("N/A")).alias("demandaforapontakw_cotacao"),
    f.coalesce(f.col("demanda_ponta_kw__c"), f.lit("N/A")).alias("demandapontakw_cotacao"),
    f.coalesce(f.col("desconto_maximo_comercial__c"), f.lit("N/A")).alias("descontomaxcomercial_cotacao"),
    f.coalesce(f.col("desconto_maximo_devido_ao_risco__c"), f.lit("N/A")).alias("descontomaxdevidorisco_cotacao"),
    f.coalesce(f.col("description"), f.lit("N/A")).alias("descricao_cotacao"),
    f.coalesce(f.col("discount"), f.lit("N/A")).alias("desconto_cotacao"),
    f.coalesce(f.col("email"), f.lit("N/A")).alias("email_cotacao"),
    f.coalesce(f.col("emailcontato__c"), f.lit("N/A")).alias("emailcontato_cotacao"),
    f.coalesce(f.col("expirationdate"), f.lit("N/A")).alias("dataValidade_cotacao"),
    f.coalesce(f.col("fax"), f.lit("N/A")).alias("fax_cotacao"),
    f.coalesce(f.col("flex__c"), f.lit("N/A")).alias("flex_cotacao"),
    f.coalesce(f.col("flex_porcentagem__c"), f.lit("N/A")).alias("flexporcentagem_cotacao"),
    f.coalesce(f.col("garantia_do_comprador__c"), f.lit("N/A")).alias("garantiadocomprador_cotacao"),
    f.coalesce(f.col("grandtotal"), f.lit("N/A")).alias("totalGeral_cotacao"),
    f.coalesce(f.col("id"), f.lit("N/A")).alias("idcotacao_cotacao"),
    f.coalesce(f.col("indice_de_reajuste_data_base__c"), f.lit("N/A")).alias("indicereajustedatabase_cotacao"),
    f.coalesce(f.col("isdeleted"), f.lit("N/A")).alias("foideletado_cotacao"),
    f.coalesce(f.col("issyncing"), f.lit("N/A")).alias("foisincronizado_cotacao"),
    f.coalesce(f.col("lastmodifiedbyid"), f.lit("N/A")).alias("ultimamodificacaopor_cotacao"),
    f.coalesce(f.col("lastmodifieddate"), f.lit("N/A")).alias("dataultimamodificacao_cotacao"),
    f.coalesce(f.col("lastreferenceddate"), f.lit("N/A")).alias("dataultimareferencia_cotacao"),
    f.coalesce(f.col("lastvieweddate"), f.lit("N/A")).alias("dataultimavizualizacao_cotacao"),
    f.coalesce(f.col("lineitemcount"), f.lit("N/A")).alias("countagemdeitens_cotacao"),
    f.coalesce(f.col("modalidade_de_negocio__c"), f.lit("N/A")).alias("modalidadenegocio_cotacao"),
    f.coalesce(f.col("modulacao__c"), f.lit("N/A")).alias("modulacao_cotacao"),
    f.coalesce(f.col("multa_antecipacao__c"), f.lit("N/A")).alias("multaantecipacao_cotacao"),
    f.coalesce(f.col("name"), f.lit("N/A")).alias("nomecotacao_cotacao"),
    f.coalesce(f.col("oferta_preco_fixo_aplicavel__c"), f.lit("N/A")).alias("ofertaprecofixoaplicavel_cotacao"),
    f.coalesce(f.col("opportunityid"), f.lit("N/A")).alias("idoportunidade_cotacao"),
    f.coalesce(f.col("ownerid"), f.lit("N/A")).alias("proprietario_cotacao"),
    f.coalesce(f.col("phone"), f.lit("N/A")).alias("telefone_cotacao"),
    f.coalesce(f.col("preco_medio_venda__c"), f.lit("N/A")).alias("precomediovenda_cotacao"),
    f.coalesce(f.col("preco_minimo_energia__c"), f.lit("N/A")).alias("precominimoenergia_cotacao"),
    f.coalesce(f.col("precoponderado__c"), f.lit("N/A")).alias("precoponderado_cotacao"),
    f.coalesce(f.col("pricebook2id"), f.lit("N/A")).alias("livrodepreco_cotacao"),
    f.coalesce(f.col("produtopotencial__c"), f.lit("N/A")).alias("produtopontencial_cotacao"),
    f.coalesce(f.col("quotenumber"), f.lit("N/A")).alias("numerocotacao_cotacao"),
    f.coalesce(f.col("quotetoaddress"), f.lit("N/A")).alias("enderecocotacao_cotacao"),
    f.coalesce(f.col("quotetocity"), f.lit("N/A")).alias("cidadecotacao_cotacao"),
    f.coalesce(f.col("quotetocountry"), f.lit("N/A")).alias("paiscotacao_cotacao"),
    f.coalesce(f.col("quotetogeocodeaccuracy"), f.lit("N/A")).alias("geocodecotacao_cotacao"),
    f.coalesce(f.col("quotetolatitude"), f.lit("N/A")).alias("latitudecotacao_cotacao"),
    f.coalesce(f.col("quotetolongitude"), f.lit("N/A")).alias("longitudecotacao_cotacao"),
    f.coalesce(f.col("quotetoname"), f.lit("N/A")).alias("nomeparacotacao_cotacao"),
    f.coalesce(f.col("quotetopostalcode"), f.lit("N/A")).alias("cepcotacao_cotacao"),
    f.coalesce(f.col("quotetostate"), f.lit("N/A")).alias("estadocotacao_cotacao"),
    f.coalesce(f.col("quotetostreet"), f.lit("N/A")).alias("enderecoparacotacao_cotacao"),
    f.coalesce(f.col("recordtypeid"), f.lit("N/A")).alias("idTipoRegistro_cotacao"),
    f.coalesce(f.col("sazonalidade__c"), f.lit("N/A")).alias("sazonalidade_cotacao"),
    f.coalesce(f.col("sazonalidade_porcentagem__c"), f.lit("N/A")).alias("sazonalidadeporcentagem_cotacao"),
    f.coalesce(f.col("shippingaddress"), f.lit("N/A")).alias("enderecofullfornecimento_cotacao"),
    f.coalesce(f.col("shippingcity"), f.lit("N/A")).alias("cidadefornecimento_cotacao"),
    f.coalesce(f.col("shippingcountry"), f.lit("N/A")).alias("paisfornecimento_cotacao"),
    f.coalesce(f.col("shippinggeocodeaccuracy"), f.lit("N/A")).alias("geocodefornecimento_cotacao"),
    f.coalesce(f.col("shippinghandling"), f.lit("N/A")).alias("manuseiofornecimento_cotacao"),
    f.coalesce(f.col("shippinglatitude"), f.lit("N/A")).alias("latitudefornecimento_cotacao"),
    f.coalesce(f.col("shippinglongitude"), f.lit("N/A")).alias("longitudefornecimento_cotacao"),
    f.coalesce(f.col("shippingname"), f.lit("N/A")).alias("nomeparafornecimento_cotacao"),
    f.coalesce(f.col("shippingpostalcode"), f.lit("N/A")).alias("cepfornecimento_cotacao"),
    f.coalesce(f.col("shippingstate"), f.lit("N/A")).alias("estadoforncecimento_cotacao"),
    f.coalesce(f.col("shippingstreet"), f.lit("N/A")).alias("enderecofornecimento_cotacao"),
    f.coalesce(f.col("sinalizador__c"), f.lit("N/A")).alias("sinalizador_cotacao"),
    f.coalesce(f.col("situacao__c"), f.lit("N/A")).alias("situacao_cotacao"),
    f.coalesce(f.col("status"), f.lit("N/A")).alias("statuscotacao_cotacao"),
    f.coalesce(f.col("submercado__c"), f.lit("N/A")).alias("submercado_cotacao"),
    f.coalesce(f.col("subtotal"), f.lit("N/A")).alias("subtotal_cotacao"),
    f.coalesce(f.col("suprimento__c"), f.lit("N/A")).alias("suprimento_cotacao"),
    f.coalesce(f.col("systemmodstamp"), f.lit("N/A")).alias("systemmodstamp_cotacao"),
    f.coalesce(f.col("tax"), f.lit("N/A")).alias("imposto_cotacao"),
    f.coalesce(f.col("telefonecontato__c"), f.lit("N/A")).alias("telefonecontato_cotacao"),
    f.coalesce(f.col("tipo_cliente__c"), f.lit("N/A")).alias("tipocliente_cotacao"),
    f.coalesce(f.col("tipo_cotacao__c"), f.lit("N/A")).alias("tipocotacao_cotacao"),
    f.coalesce(f.col("tipo_de_proposta__c"), f.lit("N/A")).alias("tipoproposta_cotacao"),
    f.coalesce(f.col("totalprice"), f.lit("N/A")).alias("precototal_cotacao"),
    f.coalesce(f.col("usina_a_ser_ofertada__c"), f.lit("N/A")).alias("usinaaserofertada_cotacao"),
    f.coalesce(f.col("volume_mwm_de_energia__c"), f.lit("N/A")).alias("volumemwmdeenergia_cotacao")
)

# montando dataframe de oportunidade
path_oportunidade = 's3://trusted-zone-echo/ods/sf/oportunidades/'
df_oportunidade = spark.read.parquet(path_oportunidade)
df_oportunidade = df_oportunidade.select(
    f.coalesce(f.col("accountid"), f.lit("N/A")).alias("idconta_oportunidade"),
    f.coalesce(f.col("ageindays"), f.lit("N/A")).alias("idadeEmDias_oportunidade"),
    f.coalesce(f.col("amount"), f.lit("N/A")).alias("valor_oportunidade"),
    f.coalesce(f.col("boleta__c"), f.lit("N/A")).alias("boleta_oportunidade"),
    f.coalesce(f.col("budget_confirmed__c"), f.lit("N/A")).alias("orcamentoConfirmado_oportunidade"),
    f.coalesce(f.col("campaignid"), f.lit("N/A")).alias("idcampanha_oportunidade"),
    f.coalesce(f.col("classificacao__c"), f.lit("N/A")).alias("classificacao_oportunidade"),
    f.coalesce(f.col("classificacao_do_produto_potencial__c"), f.lit("N/A")).alias("classificacaodoprodutopotencial_oportunidade"),
    f.coalesce(f.col("closedate"), f.lit("N/A")).alias("datafechamento_oportunidade"),
    f.coalesce(f.col("cnpj__c"), f.lit("N/A")).alias("cnpj_oportunidade"),
    f.coalesce(f.col("consumo_fora_ponta_kwh__c"), f.lit("N/A")).alias("consumoforapontakwh_oportunidade"),
    f.coalesce(f.col("consumo_mwm__c"), f.lit("N/A")).alias("consumomwm_oportunidade"),
    f.coalesce(f.col("consumo_ponta_kwh__c"), f.lit("N/A")).alias("consumopontakwh_oportunidade"),
    f.coalesce(f.col("consumo_total_kwh__c"), f.lit("N/A")).alias("consumototalkwh_oportunidade"),
    f.coalesce(f.col("contactid"), f.lit("N/A")).alias("idcontato_oportunidade"),
    f.coalesce(f.col("contractid"), f.lit("N/A")).alias("idcontrato_oportunidade"),
    f.coalesce(f.col("contrato_em_anos__c"), f.lit("N/A")).alias("anosContrato_oportunidade"),
    f.coalesce(f.col("contrato_em_anos_formula__c"), f.lit("N/A")).alias("formulaAnosContrato_oportunidade"),
    f.coalesce(f.col("cor_restricao__c"), f.lit("N/A")).alias("restricaoCor_oportunidade"),
    f.coalesce(f.col("corscore__c"), f.lit("N/A")).alias("corscore_oportunidade"),
    f.coalesce(f.col("cotacao_inicial_criada__c"), f.lit("N/A")).alias("cotacaoInicialCriada_oportunidade"),
    f.coalesce(f.col("cpf__c"), f.lit("N/A")).alias("cpf_oportunidade"),
    f.coalesce(f.col("createdbyid"), f.lit("N/A")).alias("criadopor_oportunidade"),
    f.coalesce(f.col("createddate"), f.lit("N/A")).alias("datacriacao_oportunidade"),
    f.coalesce(f.col("data_de_vigencia_contrato__c"), f.lit("N/A")).alias("datavigenciaContrato_oportunidade"),
    f.coalesce(f.col("dataassinaturacontrato__c"), f.lit("N/A")).alias("dataAssinaturaContrato_oportunidade"),
    f.coalesce(f.col("datacriacaodaproposta__c"), f.lit("N/A")).alias("dataCriacaoProposta_oportunidade"),
    f.coalesce(f.col("datafechadoeganho__c"), f.lit("N/A")).alias("dataFechadoeGanho_oportunidade"),
    f.coalesce(f.col("datafinalizacaocriacaodaproposta__c"), f.lit("N/A")).alias("dataFinalizacaoCriacaoProposta_oportunidade"),
    f.coalesce(f.col("dataultimaintegracaorisk3__c"), f.lit("N/A")).alias("dataultimaIntegracaoRisco_oportunidade"),
    f.coalesce(f.col("demanda_fora_ponta_kw__c"), f.lit("N/A")).alias("demandaforapontaKw_oportunidade"),
    f.coalesce(f.col("demanda_ponta__c"), f.lit("N/A")).alias("demandaPonta_oportunidade"),
    f.coalesce(f.col("demanda_total_kw__c"), f.lit("N/A")).alias("demandaTotal_oportunidade"),
    f.coalesce(f.col("description"), f.lit("N/A")).alias("descricao_oportunidade"),
    f.coalesce(f.col("discovery_completed__c"), f.lit("N/A")).alias("completouDiscovey_oportunidade"),
    f.coalesce(f.col("distribuidora__c"), f.lit("N/A")).alias("distribuidora_oportunidade"),
    f.coalesce(f.col("duracaocriacaodapropostadias__c"), f.lit("N/A")).alias("duracaocriacaoPropostaemDias_oportunidade"),
    f.coalesce(f.col("elegivel_motor_de_preco__c"), f.lit("N/A")).alias("elegivelMotordePreco_oportunidade"),
    f.coalesce(f.col("etapa__c"), f.lit("N/A")).alias("etapa_oportunidade"),
    f.coalesce(f.col("fatura_de_energia_anexada__c"), f.lit("N/A")).alias("faturaEnergiaAnexada_oportunidade"),
    f.coalesce(f.col("fim_de_suprimento__c"), f.lit("N/A")).alias("fimdeSuprimento_oportunidade"),
    f.coalesce(f.col("fiscal"), f.lit("N/A")).alias("fiscal_oportunidade"),
    f.coalesce(f.col("fiscalquarter"), f.lit("N/A")).alias("fiscalTrimestre_oportunidade"),
    f.coalesce(f.col("fiscalyear"), f.lit("N/A")).alias("fiscalAno_oportunidade"),
    f.coalesce(f.col("forecastcategory"), f.lit("N/A")).alias("categoriaPrevisao_oportunidade"),
    f.coalesce(f.col("forecastcategoryname"), f.lit("N/A")).alias("nomeCategoriaPrevisao_oportunidade"),
    f.coalesce(f.col("hasopenactivity"), f.lit("N/A")).alias("tematividadeAberta_oportunidade"),
    f.coalesce(f.col("hasopportunitylineitem"), f.lit("N/A")).alias("temLinhadeOportunidade_oportunidade"),
    f.coalesce(f.col("hasoverduetask"), f.lit("N/A")).alias("temTarefaVencida_oportunidade"),
    f.coalesce(f.col("iar__c"), f.lit("N/A")).alias("iar_oportunidade"),
    f.coalesce(f.col("id"), f.lit("N/A")).alias("idOportunidade_oportunidade"),
    f.coalesce(f.col("inicio_de_suprimento__c"), f.lit("N/A")).alias("inicioSuprimento_oportunidade"),
    f.coalesce(f.col("isclosed"), f.lit("N/A")).alias("foiFechado_oportunidade"),
    f.coalesce(f.col("isdeleted"), f.lit("N/A")).alias("foiDeletado_oportunidade"),
    f.coalesce(f.col("ispriorityrecord"), f.lit("N/A")).alias("registroPrioritario_oportunidade"),
    f.coalesce(f.col("iswon"), f.lit("N/A")).alias("foiGanho_oportunidade"),
    f.coalesce(f.col("lastactivitydate"), f.lit("N/A")).alias("dataultimaAtividade_oportunidade"),
    f.coalesce(f.col("lastactivityindays"), f.lit("N/A")).alias("ultimaAtividadeEmDias_oportunidade"),
    f.coalesce(f.col("lastamountchangedhistoryid"), f.lit("N/A")).alias("UltimaAlteracaoValorHistoricoID_oportunidade"),
    f.coalesce(f.col("lastclosedatechangedhistoryid"), f.lit("N/A")).alias("ulimtaDatafechamentoAlteracaohistoricoID_oportunidade"),
    f.coalesce(f.col("lastmodifiedbyid"), f.lit("N/A")).alias("ultimamodificacaopor_oportunidade"),
    f.coalesce(f.col("lastmodifieddate"), f.lit("N/A")).alias("dataultimamodificacao_oportunidade"),
    f.coalesce(f.col("lastreferenceddate"), f.lit("N/A")).alias("datadaultimareferencia_oportunidade"),
    f.coalesce(f.col("laststagechangedate"), f.lit("N/A")).alias("datadoultimoestagiodealteracao_oportunidade"),
    f.coalesce(f.col("laststagechangeindays"), f.lit("N/A")).alias("ultimaestagiodealteracaoemdias_oportunidade"),
    f.coalesce(f.col("lastvieweddate"), f.lit("N/A")).alias("dataultimavizualizacao_oportunidade"),
    f.coalesce(f.col("leadsource"), f.lit("N/A")).alias("origemdolead_oportunidade"),
    f.coalesce(f.col("loss_reason__c"), f.lit("N/A")).alias("motivoDaPerda_oportunidade"),
    f.coalesce(f.col("maiordatadeentradanafase__c"), f.lit("N/A")).alias("maiorDatadeEntradanaFase_oportunidade"),
    f.coalesce(f.col("menordatadeentradanafase__c"), f.lit("N/A")).alias("menorDatadeEntradanaFase_oportunidade"),
    f.coalesce(f.col("motivo_de_perda__c"), f.lit("N/A")).alias("motivoDePerda_oportunidade"),
    f.coalesce(f.col("name"), f.lit("N/A")).alias("nomeOportunidade_oportunidade"),
    f.coalesce(f.col("nextstep"), f.lit("N/A")).alias("proximoPasso_oportunidade"),
    f.coalesce(f.col("nivel_de_desconto_maximo__c"), f.lit("N/A")).alias("nivelDescontoMaximo_oportunidade"),
    f.coalesce(f.col("numero_restricao__c"), f.lit("N/A")).alias("numeroRestricao_oportunidade"),
    f.coalesce(f.col("numeroproposta__c"), f.lit("N/A")).alias("numeroProposta_oportunidade"),
    f.coalesce(f.col("observacoes_gerais__c"), f.lit("N/A")).alias("observacoes_oportunidade"),
    f.coalesce(f.col("ownerid"), f.lit("N/A")).alias("proprietario_oportunidade"),
    f.coalesce(f.col("parceiro__c"), f.lit("N/A")).alias("parceiro_oportunidade"),
    f.coalesce(f.col("porcentagem_score__c"), f.lit("N/A")).alias("porcentagemScore_oportunidade"),
    f.coalesce(f.col("previsao_de_ganho__c"), f.lit("N/A")).alias("previsaodeGanho_oportunidade"),
    f.coalesce(f.col("pricebook2id"), f.lit("N/A")).alias("idLivropreco_oportunidade"),
    f.coalesce(f.col("probability"), f.lit("N/A")).alias("probabilidade_oportunidade"),
    f.coalesce(f.col("pushcount"), f.lit("N/A")).alias("qntadiamentodeOprotunidade_oportunidade"),
    f.coalesce(f.col("qualificacao__c"), f.lit("N/A")).alias("qualificacao_oportunidade"),
    f.coalesce(f.col("quantidade_ucs_proposta__c"), f.lit("N/A")).alias("quantidadeUcsProposta_oportunidade"),
    f.coalesce(f.col("rating_de_risco__c"), f.lit("N/A")).alias("ratingDeRisco_oportunidade"),
    f.coalesce(f.col("recordtypeid"), f.lit("N/A")).alias("idTipoRegistro_oportunidade"),
    f.coalesce(f.col("regional__c"), f.lit("N/A")).alias("regional_oportunidade"),
    f.coalesce(f.col("roi_analysis_completed__c"), f.lit("N/A")).alias("completouAnaliseROI_oportunidade"),
    f.coalesce(f.col("situacaomigracao__c"), f.lit("N/A")).alias("situacaomigracao_oportunidade"),
    f.coalesce(f.col("sla__c"), f.lit("N/A")).alias("sla_oportunidade"),
    f.coalesce(f.col("stagename"), f.lit("N/A")).alias("nomeEstagio_oportunidade"),
    f.coalesce(f.col("submercado__c"), f.lit("N/A")).alias("submercado_oportunidade"),
    f.coalesce(f.col("syncedquoteid"), f.lit("N/A")).alias("idCotacaoDesde_oportunidade"),
    f.coalesce(f.col("tempoelaboracaodaproposta__c"), f.lit("N/A")).alias("tempoElaboracaodaProposta_oportunidade"),
    f.coalesce(f.col("tempopropostaassinada__c"), f.lit("N/A")).alias("tempoPropostaAssinada_oportunidade"),
    f.coalesce(f.col("tipo_cliente__c"), f.lit("N/A")).alias("tipoCliente_oportunidade"),
    f.coalesce(f.col("totaldeoportunidades__c"), f.lit("N/A")).alias("totaldeOportunidades_oportunidade"),
    f.coalesce(f.col("totaldeoppganhas__c"), f.lit("N/A")).alias("totaldeOportunidadesGanhas_oportunidade"),
    f.coalesce(f.col("type"), f.lit("N/A")).alias("Tipooportunidade_oportunidade"),
    f.coalesce(f.col("volume_mwm__c"), f.lit("N/A")).alias("volumeMwm_oportunidade"),
    f.coalesce(f.col("volume_total_mwm__c"), f.lit("N/A")).alias("volumeTotalMwm_oportunidade"),
    f.col("datahoraPreProcessamento").alias("datahoraProcessamento")
    )
    
# join dos dataframes de origem 
df_join = df_cotacao.join(
    df_oportunidade, \
    f.col("idOportunidade_cotacao") == f.col("idOportunidade_oportunidade"), \
    "fullouter"
    )

df = df_join.select(
    f.concat(\
            f.coalesce(f.col("idcotacao_cotacao"),f.lit("semCotacao")),\
            f.lit("_"), \
            f.coalesce(f.col("idOportunidade_oportunidade"),f.lit("semOportunidade"))\
            )\
            .alias("idFatoOportunidadeXCotacao"),
    f.col("idconta_oportunidade"),
    f.col("idadeEmDias_oportunidade"),
    f.col("valor_oportunidade"),
    f.col("boleta_oportunidade"),
    f.col("orcamentoConfirmado_oportunidade"),
    f.col("idcampanha_oportunidade"),
    f.col("classificacao_oportunidade"),
    f.col("classificacaodoprodutopotencial_oportunidade"),
    f.col("datafechamento_oportunidade"),
    f.col("cnpj_oportunidade"),
    f.col("consumoforapontakwh_oportunidade"),
    f.col("consumomwm_oportunidade"),
    f.col("consumopontakwh_oportunidade"),
    f.col("consumototalkwh_oportunidade"),
    f.col("idcontato_oportunidade"),
    f.col("idcontrato_oportunidade"),
    f.col("anosContrato_oportunidade"),
    f.col("formulaAnosContrato_oportunidade"),
    f.col("restricaoCor_oportunidade"),
    f.col("corscore_oportunidade"),
    f.col("cotacaoInicialCriada_oportunidade"),
    f.col("cpf_oportunidade"),
    f.col("datacriacao_oportunidade"),
    f.col("datavigenciaContrato_oportunidade"),
    f.col("dataAssinaturaContrato_oportunidade"),
    f.col("dataCriacaoProposta_oportunidade"),
    f.col("dataFechadoeGanho_oportunidade"),
    f.col("dataFinalizacaoCriacaoProposta_oportunidade"),
    f.col("dataultimaIntegracaoRisco_oportunidade"),
    f.col("demandaforapontaKw_oportunidade"),
    f.col("demandaPonta_oportunidade"),
    f.col("demandaTotal_oportunidade"),
    f.col("descricao_oportunidade"),
    f.col("completouDiscovey_oportunidade"),
    f.col("distribuidora_oportunidade"),
    f.col("duracaocriacaoPropostaemDias_oportunidade"),
    f.col("elegivelMotordePreco_oportunidade"),
    f.col("etapa_oportunidade"),
    f.col("faturaEnergiaAnexada_oportunidade"),
    f.col("fimdeSuprimento_oportunidade"),
    f.col("fiscal_oportunidade"),
    f.col("fiscalTrimestre_oportunidade"),
    f.col("fiscalAno_oportunidade"),
    f.col("categoriaPrevisao_oportunidade"),
    f.col("nomeCategoriaPrevisao_oportunidade"),
    f.col("tematividadeAberta_oportunidade"),
    f.col("temLinhadeOportunidade_oportunidade"),
    f.col("temTarefaVencida_oportunidade"),
    f.col("iar_oportunidade"),
    f.col("idOportunidade_oportunidade").alias("idOportunidade"),
    f.col("inicioSuprimento_oportunidade"),
    f.col("foiFechado_oportunidade"),
    f.col("foiDeletado_oportunidade"),
    f.col("registroPrioritario_oportunidade"),
    f.col("foiGanho_oportunidade"),
    f.col("dataultimaAtividade_oportunidade"),
    f.col("ultimaAtividadeEmDias_oportunidade"),
    f.col("UltimaAlteracaoValorHistoricoID_oportunidade"),
    f.col("ulimtaDatafechamentoAlteracaohistoricoID_oportunidade"),
    f.col("datadoultimoestagiodealteracao_oportunidade"),
    f.col("ultimaestagiodealteracaoemdias_oportunidade"),
    f.col("origemdolead_oportunidade"),
    f.col("motivoDaPerda_oportunidade"),
    f.col("maiorDatadeEntradanaFase_oportunidade"),
    f.col("menorDatadeEntradanaFase_oportunidade"),
    f.col("motivoDePerda_oportunidade"),
    f.col("nomeOportunidade_oportunidade").alias("nomeOportunidade"),
    f.col("proximoPasso_oportunidade"),
    f.col("nivelDescontoMaximo_oportunidade"),
    f.col("numeroRestricao_oportunidade"),
    f.col("numeroProposta_oportunidade"),
    f.col("observacoes_oportunidade"),
    f.col("parceiro_oportunidade"),
    f.col("porcentagemScore_oportunidade"),
    f.col("previsaodeGanho_oportunidade"),
    f.col("idLivropreco_oportunidade"),
    f.col("probabilidade_oportunidade"),
    f.col("qntadiamentodeOprotunidade_oportunidade"),
    f.col("qualificacao_oportunidade"),
    f.col("quantidadeUcsProposta_oportunidade"),
    f.col("ratingDeRisco_oportunidade"),
    f.col("regional_oportunidade"),
    f.col("completouAnaliseROI_oportunidade"),
    f.col("situacaomigracao_oportunidade"),
    f.col("sla_oportunidade"),
    f.col("nomeEstagio_oportunidade"),
    f.col("submercado_oportunidade"),
    f.col("idCotacaoDesde_oportunidade"),
    f.col("tempoElaboracaodaProposta_oportunidade"),
    f.col("tempoPropostaAssinada_oportunidade"),
    f.col("tipoCliente_oportunidade"),
    f.col("totaldeOportunidades_oportunidade"),
    f.col("totaldeOportunidadesGanhas_oportunidade"),
    f.col("Tipooportunidade_oportunidade"),
    f.col("volumeMwm_oportunidade"),
    f.col("volumeTotalMwm_oportunidade"),
    f.col("idconta_cotacao"),
    f.col("cidadeadicional_cotacao"),
    f.col("paisadicional_cotacao"),
    f.col("nomeadicional_cotacao"),
    f.col("cepadicional_cotacao"),
    f.col("estadoadicional_cotacao"),
    f.col("enderecoadicional_cotacao"),
    f.col("alcadadeaprovacao_cotacao"),
    f.col("cidadecobranca_cotacao"),
    f.col("paiscobranca_cotacao"),
    f.col("nomecobranca_cotacao"),
    f.col("cepcobranca_cotacao"),
    f.col("estadocobranca_cotacao"),
    f.col("enderecocobranca_cotacao"),
    f.col("clientevip_cotacao"),
    f.col("consumoforapontakwh_cotacao"),
    f.col("consumopontakwh_cotacao"),
    f.col("idcontato_cotacao"),
    f.col("idcontrato_cotacao"),
    f.col("datacriacao_cotacao"),
    f.col("custoadequacao_cotacao"),
    f.col("decontoofertado_cotacao"),
    f.col("demandaforapontakw_cotacao"),
    f.col("demandapontakw_cotacao"),
    f.col("descontomaxcomercial_cotacao"),
    f.col("descontomaxdevidorisco_cotacao"),
    f.col("descricao_cotacao"),
    f.col("desconto_cotacao"),
    f.col("email_cotacao"),
    f.col("emailcontato_cotacao"),
    f.col("dataValidade_cotacao"),
    f.col("fax_cotacao"),
    f.col("flex_cotacao"),
    f.col("flexporcentagem_cotacao"),
    f.col("garantiadocomprador_cotacao"),
    f.col("totalGeral_cotacao"),
    f.col("idcotacao_cotacao"),
    f.col("indicereajustedatabase_cotacao"),
    f.col("foideletado_cotacao"),
    f.col("foisincronizado_cotacao"),
    f.col("countagemdeitens_cotacao"),
    f.col("modalidadenegocio_cotacao"),
    f.col("modulacao_cotacao"),
    f.col("multaantecipacao_cotacao"),
    f.col("nomecotacao_cotacao"),
    f.col("ofertaprecofixoaplicavel_cotacao"),
    f.col("telefone_cotacao"),
    f.col("precomediovenda_cotacao"),
    f.col("precominimoenergia_cotacao"),
    f.col("precoponderado_cotacao"),
    f.col("livrodepreco_cotacao"),
    f.col("produtopontencial_cotacao"),
    f.col("numerocotacao_cotacao"),
    f.col("cidadecotacao_cotacao"),
    f.col("paiscotacao_cotacao"),
    f.col("nomeparacotacao_cotacao"),
    f.col("cepcotacao_cotacao"),
    f.col("estadocotacao_cotacao"),
    f.col("enderecoparacotacao_cotacao"),
    f.col("idTipoRegistro_cotacao"),
    f.col("sazonalidade_cotacao"),
    f.col("sazonalidadeporcentagem_cotacao"),
    f.col("cidadefornecimento_cotacao"),
    f.col("paisfornecimento_cotacao"),
    f.col("manuseiofornecimento_cotacao"),
    f.col("nomeparafornecimento_cotacao"),
    f.col("cepfornecimento_cotacao"),
    f.col("estadoforncecimento_cotacao"),
    f.col("enderecofornecimento_cotacao"),
    f.col("sinalizador_cotacao"),
    f.col("situacao_cotacao"),
    f.col("statuscotacao_cotacao"),
    f.col("submercado_cotacao"),
    f.col("subtotal_cotacao"),
    f.col("suprimento_cotacao"),
    f.col("imposto_cotacao"),
    f.col("telefonecontato_cotacao"),
    f.col("tipocliente_cotacao"),
    f.col("tipocotacao_cotacao"),
    f.col("tipoproposta_cotacao"),
    f.col("precototal_cotacao"),
    f.col("usinaaserofertada_cotacao"),
    f.col("volumemwmdeenergia_cotacao"),
    f.col("datahoraProcessamento")
)
df.coalesce(1).write.csv("s3://trusted-zone-echo/ods/teste/dados.csv", header=True, sep=",")
job.commit()